spring.application.name=makemytrip
server.port=8080
spring.mongodb.uri=mongodb+srv://admin:admin@main.z4fqkdu.mongodb.net/?appName=main
spring.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration